name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-dependancies:
    runs-on: ubuntu-latest

    name: "Install dependencies"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

  update-tokens:
    name: "Update design tokens"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update design tokens
        run: npm run token