name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Install-server-dependancies:
    runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - run : npm ci
  Update design tokens:
    runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - run : npm run token