name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-server-dependancies:
    runs-on: ubuntu-latest
    steps:
      - name: Install server dependencies
        uses: actions/checkout@v2
        run : npm ci